apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-uat-deployment
  labels:
    app: helloworld-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-uat
  template:
    metadata:
      labels:
        app: helloworld-uat
    spec:
      containers:
      - name: helloworld-uat-container
        image: xldevdocker/helloworld:526ed47f9c598775f81fad95feb449f42cd36604
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-uat-service
spec:
  selector:
    app: helloworld-uat
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8085
